FROM balenalib/%%BALENA_MACHINE_NAME%%-golang:latest-build AS build
WORKDIR /go/src/app
COPY /app ./
RUN go get -v && go build

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch
COPY --from=build /go/src/app .
CMD ./app --listen-address ":80"
